
<font color="#0D9DF0"><h3><B>COLETA, TRATAMENTO E ARMAZENAMENTO DE DADOS</b></h3></font>
***


#### Atividades a serem realizadas


1. **Coleta de Dados**
   - A coleta de dados é realizada por meio de arquivos do tipo texto que contém dados de pacientes, estados e dados clinicos dos pacientes.

1. **Exploração Inicial dos Dados**
   - Após a coleta é importante realizarmos a exploração inicial dos dados afim de entender sua estrutura e conteúdo.

1. **Limpeza dos Dados**
   - **Verificação de Dados Duplicados**: Utilizando scripts automatizados, removemos registros duplicados para evitar redundâncias e garantir a precisão dos dados.
   - **Tratamento de Dados Ausentes**: Identificamos e lidamos com valores ausentes, utilizando métodos automáticos para preenchimento com valores padrão ou imputação baseada em algoritmos.
  
1. **Transformação e Pré-processamento dos Dados**
   - Ajustamos os dados de acordo com as necessidades da análise. Isso pode incluir normalização, criação de variáveis derivadas, conversão de tipos de dados e agrupamento. 

1. **Integração de Dados**
   - Os dados coletados e tratados são integrados de maneira automática com sistemas existentes, garantindo que todas as informações estejam disponíveis para análise e uso imediato.

1. **Armazenamento de Dados**
   - Após o tratamento e a integração, os dados são armazenados em arquivo único e estruturado.

#### Importação das bibliotecas

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import statistics as st

#### 1. Coleta de Dados
O primeiro passo é identificar e coletar as fontes de dados necessárias. Isso pode envolver a extração de dados de bancos de dados, arquivos CSV, planilhas, APIs ou até mesmo web scraping. É essencial garantir que os dados coletados sejam relevantes para os objetivos do projeto e provenientes de fontes confiáveis.
***

In [2]:
df_clinicos = pd.read_csv('C:\\Users\\negri\\OneDrive\\Documentos\\GitHub\\Hashtag_AnaliseDados\\Python\\Cursos\\PUC Ciência de Dados\\Projetos\\02_Análise de Dados de Pacientes\\data\\raw\\dados_clinicos.csv', sep='|')
df_pacientes = pd.read_csv('C:\\Users\\negri\\OneDrive\\Documentos\\GitHub\\Hashtag_AnaliseDados\\Python\\Cursos\\PUC Ciência de Dados\\Projetos\\02_Análise de Dados de Pacientes\\data\\raw\\dados_pacientes.csv', sep=';')
df_região = pd.read_csv('C:\\Users\\negri\\OneDrive\\Documentos\\GitHub\\Hashtag_AnaliseDados\\Python\\Cursos\\PUC Ciência de Dados\\Projetos\\02_Análise de Dados de Pacientes\\data\\raw\\estado_regiao.csv', sep=';', encoding='latin-1')

#df_região.head(5)
#df_pacientes.head(5)
#df_clinicos.head(5)

In [3]:
display(df_região.head(5))

   id_estado sigla    estado    regiao    pais
0          1    AC      Acre     Norte  Brasil
1          2    AL   Alagoas  Nordeste  Brasil
2          3    AP     Amapá     Norte  Brasil
3          4    AM  Amazonas     Norte  Brasil
4          5    BA     Bahia  Nordeste  Brasil

In [4]:
display(df_pacientes.head(5))

,id_cliente,idade,classe_trabalho,escolaridade,id_estado,estado_civil,raca,qtde_filhos,salario
0,1,39,Servidor Público,Ensino Médio Completo,2,Solteiro,Branco,2.0,4754
1,2,50,Autônomo,Superior Incompleto,24,Casado,Branco,1.0,3923
2,3,38,Funcionário Setor Privado,Ensino Médio Incompleto,4,Divorciado,Branco,0.0,1100
3,4,53,Funcionário Setor Privado,Ensino Médio Incompleto,24,Casado,Negro,1.0,1100
4,5,28,Funcionário Setor Privado,Ensino Médio Completo,15,Casado,Negro,0.0,3430

In [5]:
display(df_clinicos.head(5))

   id_cliente   peso  colesterol     genero
0           1  152.7       203.9  Masculino
1           2  184.8       233.8  Masculino
2           3  152.1       210.4  Masculino
3           4  139.8       196.8  Masculino
4           5  182.4       215.8   Feminino

#### 2. Exploração Inicial dos Dados
Após coletar os dados, é importante explorar o conjunto de dados para entender sua estrutura e conteúdo. Nessa etapa, verificamos a quantidade de dados, os tipos de variáveis, as primeiras linhas e a presença de valores ausentes ou discrepantes. Ferramentas como head(), info() e describe() no Pandas ajudam a fazer uma análise inicial.
***

##### Visualização de Dados

In [6]:
df_clinicos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10301 entries, 0 to 10300
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id_cliente  10301 non-null  int64
 1   peso        10288 non-null  float64
 2   colesterol  10301 non-null  float64
 3   genero      10291 non-null  object
dtypes: float64(2), int64(1), object(1)
memory usage: 322.0+ KB

In [7]:
df_região.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id_estado  36 non-null     int64
 1   sigla      36 non-null     object
 2   estado     36 non-null     object
 3   regiao     36 non-null     object
 4   pais       36 non-null     object
dtypes: int64(1), object(4)
memory usage: 1.5+ KB

In [8]:
df_pacientes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8084 entries, 0 to 8083
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_cliente       8084 non-null   int64
 1   idade            8084 non-null   int64
 2   classe_trabalho  7690 non-null   object
 3   escolaridade     8084 non-null   object
 4   id_estado        8084 non-null   int64
 5   estado_civil     8084 non-null   object
 6   raca             8084 non-null   object
 7   qtde_filhos      8074 non-null   float64
 8   salario          8084 non-null   int64
dtypes: float64(1), int64(4), object(4)
memory usage: 568.5+ KB

<font color="#0D9DF0"><h5>Análise Descritiva dos Dados</h5></font>
A análise descritiva é um aprofundamento que visa quantificar e resumir as principais características dos dados. Nessa fase, usamos estatísticas como média, mediana, moda, variância e desvio padrão para descrever de forma quantitativa os dados e compreender melhor a distribuição das variáveis. Ela é mais estruturada e voltada para a compreensão detalhada das propriedades dos dados, gerando métricas e resumos numéricos que ajudam a validar hipóteses ou descrever comportamentos observados.
***

In [9]:
df_clinicos.describe()

         id_cliente          peso    colesterol
count  10301.000000  10288.000000  10301.000000
mean    4887.986603    124.569868    179.362149
std     2917.438919     43.343467     36.358041
min        1.000000      1.000000     94.600000
25%     2275.000000     87.200000    149.300000
50%     4850.000000    124.300000    178.800000
75%     7425.000000    161.900000    209.900000
max    10000.000000    200.000000    267.100000

In [10]:
df_região.describe()

       id_estado
count   36.00000
mean    14.00000
std      6.96522
min      1.00000
25%      9.75000
50%     14.00000
75%     18.25000
max     27.00000

In [11]:
df_pacientes.describe()

        id_cliente        idade    id_estado  qtde_filhos       salario
count  8084.000000  8084.000000  8084.000000  8074.000000   8084.000000
mean   3963.346116    38.473652    14.085725     2.402403   3166.960045
std    2324.444621    13.568186     7.818012     1.703226   3050.503185
min       1.000000    17.000000     1.000000     0.000000      0.000000
25%    1936.750000    28.000000     7.000000     1.000000   1100.000000
50%    3957.500000    37.000000    14.000000     2.000000   2410.500000
75%    5978.250000    47.000000    21.000000     4.000000   3639.000000
max    7999.000000    90.000000    27.000000     5.000000  19994.000000

##### Informações Gerais do Dataframe

A função info() do Pandas fornece um resumo rápido e útil sobre um DataFrame. Ao chamar DataFrame.info(), você obtém informações como:

- Número total de entradas (linhas) e colunas
- Nome e tipo de dados de cada coluna
- Quantidade de valores não nulos em cada coluna
- Uso de memória total do DataFrame

É uma função essencial para a exploração inicial dos dados, pois ajuda a identificar colunas com dados ausentes e entender a estrutura geral do DataFrame rapidamente.

In [12]:
df_pacientes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8084 entries, 0 to 8083
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_cliente       8084 non-null   int64
 1   idade            8084 non-null   int64
 2   classe_trabalho  7690 non-null   object
 3   escolaridade     8084 non-null   object
 4   id_estado        8084 non-null   int64
 5   estado_civil     8084 non-null   object
 6   raca             8084 non-null   object
 7   qtde_filhos      8074 non-null   float64
 8   salario          8084 non-null   int64
dtypes: float64(1), int64(4), object(4)
memory usage: 568.5+ KB

In [13]:
df_clinicos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10301 entries, 0 to 10300
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id_cliente  10301 non-null  int64
 1   peso        10288 non-null  float64
 2   colesterol  10301 non-null  float64
 3   genero      10291 non-null  object
dtypes: float64(2), int64(1), object(1)
memory usage: 322.0+ KB

In [14]:
df_região.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id_estado  36 non-null     int64
 1   sigla      36 non-null     object
 2   estado     36 non-null     object
 3   regiao     36 non-null     object
 4   pais       36 non-null     object
dtypes: int64(1), object(4)
memory usage: 1.5+ KB

#### 3. Limpeza de Dados
A limpeza de dados é crucial para garantir a qualidade da análise. Inclui tratamento de valores ausentes, remoção de duplicatas, padronização de formatos e exclusão de registros irrelevantes. Durante essa etapa, transformamos os dados brutos em dados prontos para análise, eliminando inconsistências e outliers que possam distorcer os resultados.
***

<font color="#0D9DF0"><h5>Análise de Dados Duplicados</h5></font>
Dados duplicados ocorrem quando registros iguais são inseridos mais de uma vez, o que pode inflar ou distorcer análises.

In [15]:
id_repetidos = df_pacientes[df_pacientes.duplicated()].set_index('id_cliente')
print(f"Número de Registros Duplicados: {id_repetidos.shape[0]}")

lista = id_repetidos.index.tolist()
print(lista)

Número de Registros Duplicados: 85
[472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556]

In [16]:
id_repetidos = df_clinicos[df_clinicos.duplicated()].set_index('id_cliente')
print(f"Número de Registros Duplicados: {id_repetidos.shape[0]}")

lista = id_repetidos.index.tolist()
print(lista)

Número de Registros Duplicados: 301
[1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044, 1045, 1046, 1047, 1048, 1049, 1050, 1051, 1052, 1053, 1054, 1055, 1056, 1057, 1058, 1059, 1060, 1061, 1062, 1063, 1064, 1065, 1066, 1067, 1068, 1069, 1070, 1071, 1072, 1073, 1074, 1075, 1076, 1077, 1078, 1079, 1080, 1081, 1082, 1083, 1084, 1085, 1086, 1087, 1088, 1089, 1090, 1091, 1092, 1093, 1094, 1095, 1096, 1097, 1098, 1099, 1100, 1101, 1102, 1103, 1104, 1105, 1106, 1107, 1108, 1109, 1110, 1111, 1112, 1113, 1114, 1115, 1116, 1117, 1118, 1119, 1120, 1121, 1122, 1123, 1124, 1125, 1126, 1127, 1128, 1129, 1130, 1131, 1132, 1133, 1134, 1135, 1136, 1137, 1138, 1139, 1140, 1141, 1142, 1143, 1144, 1145, 1146, 1147, 1148, 1149, 1150, 1151, 1152, 1153, 1154, 1155, 1156, 1157, 1158, 1159, 1160, 1161, 1162, 1163, 1164, 1165, 1166, 1167, 1168, 1169, 1170, 1171, 1172, 1173, 1174, 1175, 1176, 1177, 1178, 1179, 1180, 1181, 1182, 1183, 1184, 1185, 1186, 1187, 1188, 1189, 1190, 1191, 1192, 1193, 1194, 1195, 1196, 1197, 1198, 1199, 1200, 1201, 1202, 1203, 1204, 1205, 1206, 1207, 1208, 1209, 1210, 1211, 1212, 1213, 1214, 1215, 1216, 1217, 1218, 1219, 1220, 1221, 1222, 1223, 1224, 1225, 1226, 1227, 1228, 1229, 1230, 1231, 1232, 1233, 1234, 1235, 1236, 1237, 1238, 1239, 1240, 1241, 1242, 1243, 1244, 1245, 1246, 1247, 1248, 1249, 1250, 1251, 1252, 1253, 1254, 1255, 1256, 1257, 1258, 1259, 1260, 1261, 1262, 1263, 1264, 1265, 1266, 1267, 1268, 1269, 1270, 1271, 1272, 1273, 1274, 1275, 1276, 1277, 1278, 1279, 1280, 1281, 1282, 1283, 1284, 1285, 1286, 1287, 1288, 1289, 1290, 1291, 1292, 1293, 1294, 1295, 1296, 1297, 1298, 1299, 1300]

In [17]:
id_repetidos = df_região[df_região.duplicated()].set_index('id_estado')
print(f"Número de Registros Duplicados: {id_repetidos.shape[0]}")

lista = id_repetidos.index.tolist()
print(lista)

Número de Registros Duplicados: 9
[10, 11, 12, 13, 14, 15, 16, 17, 18]

<font color="#0098A6"><h5>Eliminando os dados duplicados</h5></font>

In [18]:
df_pacientes.drop_duplicates(inplace=True)
display(df_pacientes.info())

<class 'pandas.core.frame.DataFrame'>
Index: 7999 entries, 0 to 8083
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_cliente       7999 non-null   int64
 1   idade            7999 non-null   int64
 2   classe_trabalho  7612 non-null   object
 3   escolaridade     7999 non-null   object
 4   id_estado        7999 non-null   int64
 5   estado_civil     7999 non-null   object
 6   raca             7999 non-null   object
 7   qtde_filhos      7989 non-null   float64
 8   salario          7999 non-null   int64
dtypes: float64(1), int64(4), object(4)
memory usage: 624.9+ KB

None

In [19]:
df_clinicos.drop_duplicates(inplace=True)
display(df_clinicos.info())

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 0 to 10300
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id_cliente  10000 non-null  int64
 1   peso        9987 non-null   float64
 2   colesterol  10000 non-null  float64
 3   genero      9990 non-null   object
dtypes: float64(2), int64(1), object(1)
memory usage: 390.6+ KB

None

In [20]:
df_região.drop_duplicates(inplace=True)
display(df_região.info())

<class 'pandas.core.frame.DataFrame'>
Index: 27 entries, 0 to 35
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id_estado  27 non-null     int64
 1   sigla      27 non-null     object
 2   estado     27 non-null     object
 3   regiao     27 non-null     object
 4   pais       27 non-null     object
dtypes: int64(1), object(4)
memory usage: 1.3+ KB

None

<font color="#0D9DF0"><h5>Análise de Dados Ausentes</h5></font>
Valores ausentes são comuns em bases de dados reais. Eles ocorrem por diversos motivos, como falhas na coleta de dados ou informações não informadas. Existem diferentes estratégias para lidar com esses valores:

In [21]:
df_clinicos.isnull().sum()

id_cliente     0
peso          13
colesterol     0
genero        10
dtype: int64

In [22]:
df_pacientes.isnull().sum()

id_cliente           0
idade                0
classe_trabalho    387
escolaridade         0
id_estado            0
estado_civil         0
raca                 0
qtde_filhos         10
salario              0
dtype: int64

In [23]:
df_região.isnull().sum()

id_estado    0
sigla        0
estado       0
regiao       0
pais         0
dtype: int64

#### Corrigindo dados ausentes
1. Média para as variáveis numéricas 
1. Moda para as variáveis categóricas

In [24]:
df_clinicos['peso'].fillna(df_clinicos['peso'].median().round(2), inplace=True) 
#df_clinicos['genero'].fillna(df_clinicos['genero'].mode()[0], inplace=True)
df_clinicos['genero'].fillna("Não Informado", inplace=True)

C:\Users\negri\AppData\Local\Temp\ipykernel_15208\3106909859.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clinicos['peso'].fillna(df_clinicos['peso'].median().round(2), inplace=True)
C:\Users\negri\AppData\Local\Temp\ipykernel_15208\3106909859.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clinicos['genero'].fillna("Não Informado", inplace=True)

In [25]:
df_clinicos.isnull().sum()

id_cliente    0
peso          0
colesterol    0
genero        0
dtype: int64

In [26]:
df_pacientes['qtde_filhos'].fillna(df_pacientes['qtde_filhos'].median().round(0), inplace=True)
#df_pacientes['classe_trabalho'].fillna(df_pacientes['classe_trabalho'].mode()[0], inplace=True)
df_pacientes['classe_trabalho'].fillna("Não Informado", inplace=True)

C:\Users\negri\AppData\Local\Temp\ipykernel_15208\2114852702.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_pacientes['qtde_filhos'].fillna(df_pacientes['qtde_filhos'].median().round(0), inplace=True)
C:\Users\negri\AppData\Local\Temp\ipykernel_15208\2114852702.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_pacientes['classe_trabalho'].fillna("Não Informado", inplace=True)

In [27]:
df_pacientes.isnull().sum()

id_cliente         0
idade              0
classe_trabalho    0
escolaridade       0
id_estado          0
estado_civil       0
raca               0
qtde_filhos        0
salario            0
dtype: int64

In [28]:
df_pacientes['classe_trabalho'].value_counts()

classe_trabalho
Funcionário Setor Privado    5382
Autônomo                      588
Empresário                    496
Não Informado                 387
Servidor Público              299
MEI                           275
Aposentado                    267
Funcionário Público           216
Menor Aprendiz                 85
Desempregado                    3
Estagiário                      1
Name: count, dtype: int64

#### 4. Transformação e Pré-processamento dos Dados
Nesta etapa, ajustamos os dados de acordo com as necessidades da análise. Isso pode incluir normalização, criação de variáveis derivadas, conversão de tipos de dados e agrupamento. As transformações tornam os dados mais fáceis de interpretar e podem incluir operações matemáticas e agregações.
***

In [29]:
df_pacientes.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7999 entries, 0 to 8083
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_cliente       7999 non-null   int64
 1   idade            7999 non-null   int64
 2   classe_trabalho  7999 non-null   object
 3   escolaridade     7999 non-null   object
 4   id_estado        7999 non-null   int64
 5   estado_civil     7999 non-null   object
 6   raca             7999 non-null   object
 7   qtde_filhos      7999 non-null   float64
 8   salario          7999 non-null   int64
dtypes: float64(1), int64(4), object(4)
memory usage: 624.9+ KB

In [30]:
df_pacientes['idade'] = pd.to_numeric(df_pacientes['idade'], errors='coerce')
df_pacientes['qtde_filhos'] = pd.to_numeric(df_pacientes['qtde_filhos'], errors='coerce')
df_pacientes['estado_civil'] = df_pacientes['estado_civil'].astype('string')
df_pacientes['raca'] = df_pacientes['raca'].astype('string')
df_pacientes['classe_trabalho'] = df_pacientes['classe_trabalho'].astype('string')
df_pacientes['escolaridade'] = df_pacientes['escolaridade'].astype('string')

In [31]:
df_pacientes.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7999 entries, 0 to 8083
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_cliente       7999 non-null   int64
 1   idade            7999 non-null   int64
 2   classe_trabalho  7999 non-null   string
 3   escolaridade     7999 non-null   string
 4   id_estado        7999 non-null   int64
 5   estado_civil     7999 non-null   string
 6   raca             7999 non-null   string
 7   qtde_filhos      7999 non-null   float64
 8   salario          7999 non-null   int64
dtypes: float64(1), int64(4), string(4)
memory usage: 624.9 KB

In [32]:
df_clinicos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 0 to 10300
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id_cliente  10000 non-null  int64
 1   peso        10000 non-null  float64
 2   colesterol  10000 non-null  float64
 3   genero      10000 non-null  object
dtypes: float64(2), int64(1), object(1)
memory usage: 390.6+ KB

In [33]:
df_clinicos['genero'] = df_clinicos['genero'].astype('string')

In [34]:
df_clinicos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 0 to 10300
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id_cliente  10000 non-null  int64
 1   peso        10000 non-null  float64
 2   colesterol  10000 non-null  float64
 3   genero      10000 non-null  string
dtypes: float64(2), int64(1), string(1)
memory usage: 390.6 KB

In [35]:
df_região.info()

<class 'pandas.core.frame.DataFrame'>
Index: 27 entries, 0 to 35
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id_estado  27 non-null     int64
 1   sigla      27 non-null     object
 2   estado     27 non-null     object
 3   regiao     27 non-null     object
 4   pais       27 non-null     object
dtypes: int64(1), object(4)
memory usage: 1.3+ KB

In [36]:
df_região['sigla'] = df_região['sigla'].astype('string')
df_região['estado'] = df_região['estado'].astype('string')
df_região['regiao'] = df_região['regiao'].astype('string')
df_região['pais'] = df_região['pais'].astype('string')

In [37]:
df_região.info()

<class 'pandas.core.frame.DataFrame'>
Index: 27 entries, 0 to 35
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id_estado  27 non-null     int64
 1   sigla      27 non-null     string
 2   estado     27 non-null     string
 3   regiao     27 non-null     string
 4   pais       27 non-null     string
dtypes: int64(1), string(4)
memory usage: 1.3 KB

#### 5. Integração de Dados
A integração de dados é um processo essencial em projetos de análise, especialmente quando os dados vêm de fontes diferentes. Muitas vezes, informações importantes estão dispersas em múltiplos bancos de dados, planilhas, APIs ou sistemas, e cada fonte pode conter uma parte relevante do contexto necessário para uma análise completa. A integração permite combinar essas fontes em uma única visão consolidada, tornando possível analisar o conjunto de dados de forma mais rica e abrangente.
***

In [38]:
df_pacientes.head(5)

,id_cliente,idade,classe_trabalho,escolaridade,id_estado,estado_civil,raca,qtde_filhos,salario
0,1,39,Servidor Público,Ensino Médio Completo,2,Solteiro,Branco,2.0,4754
1,2,50,Autônomo,Superior Incompleto,24,Casado,Branco,1.0,3923
2,3,38,Funcionário Setor Privado,Ensino Médio Incompleto,4,Divorciado,Branco,0.0,1100
3,4,53,Funcionário Setor Privado,Ensino Médio Incompleto,24,Casado,Negro,1.0,1100
4,5,28,Funcionário Setor Privado,Ensino Médio Completo,15,Casado,Negro,0.0,3430

In [39]:
df_integrado = df_pacientes.merge(df_clinicos, on='id_cliente', how='inner').merge(df_região, left_on='id_estado', right_on='id_estado', how='inner')
display(df_integrado.head(5))

,id_cliente,idade,classe_trabalho,escolaridade,id_estado,estado_civil,raca,qtde_filhos,salario,peso,colesterol,genero,sigla,estado,regiao,pais
0,1,39,Servidor Público,Ensino Médio Completo,2,Solteiro,Branco,2.0,4754,152.7,203.9,Masculino,AL,Alagoas,Nordeste,Brasil
1,2,50,Autônomo,Superior Incompleto,24,Casado,Branco,1.0,3923,184.8,233.8,Masculino,SC,Santa Catarina,Sul,Brasil
2,3,38,Funcionário Setor Privado,Ensino Médio Incompleto,4,Divorciado,Branco,0.0,1100,152.1,210.4,Masculino,AM,Amazonas,Norte,Brasil
3,4,53,Funcionário Setor Privado,Ensino Médio Incompleto,24,Casado,Negro,1.0,1100,139.8,196.8,Masculino,SC,Santa Catarina,Sul,Brasil
4,5,28,Funcionário Setor Privado,Ensino Médio Completo,15,Casado,Negro,0.0,3430,182.4,215.8,Feminino,PB,Paraíba,Nordeste,Brasil

In [40]:
df_integrado_copy = df_integrado[['id_cliente', 'idade', 'genero', 'estado_civil', 'peso', 'colesterol', 'id_estado', 'sigla', 'estado', 'regiao']]
display(df_integrado_copy.head(5))

,id_cliente,idade,genero,estado_civil,peso,colesterol,id_estado,sigla,estado,regiao
0,1,39,Masculino,Solteiro,152.7,203.9,2,AL,Alagoas,Nordeste
1,2,50,Masculino,Casado,184.8,233.8,24,SC,Santa Catarina,Sul
2,3,38,Masculino,Divorciado,152.1,210.4,4,AM,Amazonas,Norte
3,4,53,Masculino,Casado,139.8,196.8,24,SC,Santa Catarina,Sul
4,5,28,Feminino,Casado,182.4,215.8,15,PB,Paraíba,Nordeste

#### 6. Armazenamento de Dados

Após o tratamento e a limpeza dos dados, o armazenamento é um passo importante para garantir que o trabalho realizado seja preservado e que os dados estejam prontos para futuras análises. O armazenamento de dados tratados facilita o acesso rápido e seguro às informações, evitando a necessidade de repetir as etapas de limpeza e processamento.

***

In [41]:
#df_integrado = pd.export_csv('C:\\Users\\negri\\OneDrive\\Documentos\\GitHub\\Hashtag_AnaliseDados\\Python\\Cursos\\PUC Ciência de Dados\\Projetos\\02_Análise de Dados de Pacientes\\data\\processed', index=False, encode='utf-8')